// Generation 3 (252-386) - Ruby, Sapphire, Emerald
// Hoenn Region Pokémon
export const pokemonRSE = [
  { id: 252, name: 'treecko', types: ['grass'] },
  { id: 253, name: 'grovyle', types: ['grass'] },
  { id: 254, name: 'sceptile', types: ['grass'] },
  {
    id: 254.1,
    name: 'sceptile-mega',
    types: ['grass', 'dragon'],
    form: 'Mega Evolution',
  },
  { id: 255, name: 'torchic', types: ['fire'] },
  { id: 256, name: 'combusken', types: ['fire', 'fighting'] },
  { id: 257, name: 'blaziken', types: ['fire', 'fighting'] },
  {
    id: 257.1,
    name: 'blaziken-mega',
    types: ['fire', 'fighting'],
    form: 'Mega Evolution',
  },
  { id: 258, name: 'mudkip', types: ['water'] },
  { id: 259, name: 'marshtomp', types: ['water', 'ground'] },
  { id: 260, name: 'swampert', types: ['water', 'ground'] },
  {
    id: 260.1,
    name: 'swampert-mega',
    types: ['water', 'ground'],
    form: 'Mega Evolution',
  },
  { id: 261, name: 'poochyena', types: ['dark'] },
  { id: 262, name: 'mightyena', types: ['dark'] },
  { id: 263, name: 'zigzagoon', types: ['normal'] },
  {
    id: 263.1,
    name: 'zigzagoon-galarian',
    types: ['dark', 'normal'],
    region: 'Galar',
  },
  { id: 264, name: 'linoone', types: ['normal'] },
  {
    id: 264.1,
    name: 'linoone-galarian',
    types: ['dark', 'normal'],
    region: 'Galar',
  },
  { id: 270, name: 'lotad', types: ['water', 'grass'] },
  { id: 271, name: 'lombre', types: ['water', 'grass'] },
  { id: 272, name: 'ludicolo', types: ['water', 'grass'] },
  { id: 273, name: 'seedot', types: ['grass'] },
  { id: 274, name: 'nuzleaf', types: ['grass', 'dark'] },
  { id: 275, name: 'shiftry', types: ['grass', 'dark'] },
  {
    id: 280,
    name: 'ralts',
    types: ['psychic', 'fairy'],
    generationTypes: { 3: ['psychic'], 6: ['psychic', 'fairy'] },
  },
  {
    id: 281,
    name: 'kirlia',
    types: ['psychic', 'fairy'],
    generationTypes: { 3: ['psychic'], 6: ['psychic', 'fairy'] },
  },
  {
    id: 282,
    name: 'gardevoir',
    types: ['psychic', 'fairy'],
    generationTypes: { 3: ['psychic'], 6: ['psychic', 'fairy'] },
  },
  {
    id: 282.1,
    name: 'gardevoir-mega',
    types: ['psychic', 'fairy'],
    form: 'Mega Evolution',
  },
  { id: 287, name: 'slakoth', types: ['normal'] },
  { id: 288, name: 'vigoroth', types: ['normal'] },
  { id: 289, name: 'slaking', types: ['normal'] },
  { id: 290, name: 'nincada', types: ['bug', 'ground'] },
  { id: 291, name: 'ninjask', types: ['bug', 'flying'] },
  { id: 292, name: 'shedinja', types: ['bug', 'ghost'] },
  { id: 295, name: 'exploud', types: ['normal'] },
  { id: 296, name: 'makuhita', types: ['fighting'] },
  { id: 297, name: 'hariyama', types: ['fighting'] },
  {
    id: 298,
    name: 'azurill',
    types: ['normal', 'fairy'],
    generationTypes: { 3: ['normal'], 6: ['normal', 'fairy'] },
  },
  { id: 300, name: 'skitty', types: ['normal'] },
  { id: 301, name: 'delcatty', types: ['normal'] },
  { id: 302, name: 'sableye', types: ['dark', 'ghost'] },
  {
    id: 302.1,
    name: 'sableye-mega',
    types: ['dark', 'ghost'],
    form: 'Mega Evolution',
  },
  {
    id: 303,
    name: 'mawile',
    types: ['steel', 'fairy'],
    generationTypes: { 3: ['steel'], 6: ['steel', 'fairy'] },
  },
  {
    id: 303.1,
    name: 'mawile-mega',
    types: ['steel', 'fairy'],
    form: 'Mega Evolution',
  },
  { id: 304, name: 'aron', types: ['steel', 'rock'] },
  { id: 305, name: 'lairon', types: ['steel', 'rock'] },
  { id: 306, name: 'aggron', types: ['steel', 'rock'] },
  { id: 306.1, name: 'aggron-mega', types: ['steel'], form: 'Mega Evolution' },
  { id: 307, name: 'meditite', types: ['fighting', 'psychic'] },
  { id: 308, name: 'medicham', types: ['fighting', 'psychic'] },
  {
    id: 308.1,
    name: 'medicham-mega',
    types: ['fighting', 'psychic'],
    form: 'Mega Evolution',
  },
  { id: 309, name: 'electrike', types: ['electric'] },
  { id: 310, name: 'manectric', types: ['electric'] },
  {
    id: 310.1,
    name: 'manectric-mega',
    types: ['electric'],
    form: 'Mega Evolution',
  },
  { id: 311, name: 'plusle', types: ['electric'] },
  { id: 312, name: 'minun', types: ['electric'] },
  { id: 313, name: 'volbeat', types: ['bug'] },
  { id: 314, name: 'illumise', types: ['bug'] },
  { id: 315, name: 'roselia', types: ['grass', 'poison'] },
  { id: 316, name: 'gulpin', types: ['poison'] },
  { id: 317, name: 'swalot', types: ['poison'] },
  { id: 318, name: 'carvanha', types: ['water', 'dark'] },
  { id: 319, name: 'sharpedo', types: ['water', 'dark'] },
  {
    id: 319.1,
    name: 'sharpedo-mega',
    types: ['water', 'dark'],
    form: 'Mega Evolution',
  },
  { id: 320, name: 'wailmer', types: ['water'] },
  { id: 321, name: 'wailord', types: ['water'] },
  { id: 322, name: 'numel', types: ['fire', 'ground'] },
  { id: 323, name: 'camerupt', types: ['fire', 'ground'] },
  {
    id: 323.1,
    name: 'camerupt-mega',
    types: ['fire', 'ground'],
    form: 'Mega Evolution',
  },
  { id: 324, name: 'torkoal', types: ['fire'] },
  { id: 325, name: 'spoink', types: ['psychic'] },
  { id: 326, name: 'grumpig', types: ['psychic'] },
  { id: 327, name: 'spinda', types: ['normal'] },
  { id: 328, name: 'trapinch', types: ['ground'] },
  { id: 329, name: 'vibrava', types: ['ground', 'dragon'] },
  { id: 330, name: 'flygon', types: ['ground', 'dragon'] },
  { id: 331, name: 'cacnea', types: ['grass'] },
  { id: 332, name: 'cacturne', types: ['grass', 'dark'] },
  { id: 333, name: 'swablu', types: ['normal', 'flying'] },
  { id: 334, name: 'altaria', types: ['dragon', 'flying'] },
  {
    id: 334.1,
    name: 'altaria-mega',
    types: ['dragon', 'fairy'],
    form: 'Mega Evolution',
  },
  { id: 335, name: 'zangoose', types: ['normal'] },
  { id: 336, name: 'seviper', types: ['poison'] },
  { id: 337, name: 'lunatone', types: ['rock', 'psychic'] },
  { id: 338, name: 'solrock', types: ['rock', 'psychic'] },
  { id: 339, name: 'barboach', types: ['water', 'ground'] },
  { id: 340, name: 'whiscash', types: ['water', 'ground'] },
  { id: 341, name: 'corphish', types: ['water'] },
  { id: 342, name: 'crawdaunt', types: ['water', 'dark'] },
  { id: 343, name: 'baltoy', types: ['ground', 'psychic'] },
  { id: 344, name: 'claydol', types: ['ground', 'psychic'] },
  { id: 345, name: 'lileep', types: ['rock', 'grass'] },
  { id: 346, name: 'cradily', types: ['rock', 'grass'] },
  { id: 347, name: 'anorith', types: ['rock', 'bug'] },
  { id: 348, name: 'armaldo', types: ['rock', 'bug'] },
  { id: 349, name: 'feebas', types: ['water'] },
  { id: 350, name: 'milotic', types: ['water'] },
  { id: 351, name: 'castform', types: ['normal'] },
  { id: 352, name: 'kecleon', types: ['normal'] },
  { id: 353, name: 'shuppet', types: ['ghost'] },
  { id: 354, name: 'banette', types: ['ghost'] },
  { id: 354.1, name: 'banette-mega', types: ['ghost'], form: 'Mega Evolution' },
  { id: 355, name: 'duskull', types: ['ghost'] },
  { id: 356, name: 'dusclops', types: ['ghost'] },
  { id: 357, name: 'tropius', types: ['grass', 'flying'] },
  { id: 358, name: 'chimecho', types: ['psychic'] },
  { id: 359, name: 'absol', types: ['dark'] },
  { id: 359.1, name: 'absol-mega', types: ['dark'], form: 'Mega Evolution' },
  { id: 360, name: 'wynaut', types: ['psychic'] },
  { id: 361, name: 'snorunt', types: ['ice'] },
  { id: 362, name: 'glalie', types: ['ice'] },
  { id: 362.1, name: 'glalie-mega', types: ['ice'], form: 'Mega Evolution' },
  { id: 363, name: 'spheal', types: ['ice', 'water'] },
  { id: 364, name: 'sealeo', types: ['ice', 'water'] },
  { id: 365, name: 'walrein', types: ['ice', 'water'] },
  { id: 366, name: 'clamperl', types: ['water'] },
  { id: 367, name: 'huntail', types: ['water'] },
  { id: 368, name: 'gorebyss', types: ['water'] },
  { id: 369, name: 'relicanth', types: ['water', 'rock'] },
  { id: 370, name: 'luvdisc', types: ['water'] },
  { id: 371, name: 'bagon', types: ['dragon'] },
  { id: 372, name: 'shelgon', types: ['dragon'] },
  { id: 373, name: 'salamence', types: ['dragon', 'flying'] },
  {
    id: 373.1,
    name: 'salamence-mega',
    types: ['dragon', 'flying'],
    form: 'Mega Evolution',
  },
  { id: 374, name: 'beldum', types: ['steel', 'psychic'] },
  { id: 375, name: 'metang', types: ['steel', 'psychic'] },
  { id: 376, name: 'metagross', types: ['steel', 'psychic'] },
  {
    id: 376.1,
    name: 'metagross-mega',
    types: ['steel', 'psychic'],
    form: 'Mega Evolution',
  },
  { id: 377, name: 'regirock', types: ['rock'] },
  { id: 378, name: 'regice', types: ['ice'] },
  { id: 379, name: 'registeel', types: ['steel'] },
  { id: 380, name: 'latias', types: ['dragon', 'psychic'] },
  {
    id: 380.1,
    name: 'latias-mega',
    types: ['dragon', 'psychic'],
    form: 'Mega Evolution',
  },
  { id: 381, name: 'latios', types: ['dragon', 'psychic'] },
  {
    id: 381.1,
    name: 'latios-mega',
    types: ['dragon', 'psychic'],
    form: 'Mega Evolution',
  },
  { id: 382, name: 'kyogre', types: ['water'] },
  {
    id: 382.1,
    name: 'kyogre-primal',
    types: ['water'],
    form: 'Primal Reversion',
  },
  { id: 383, name: 'groudon', types: ['ground'] },
  {
    id: 383.1,
    name: 'groudon-primal',
    types: ['ground', 'fire'],
    form: 'Primal Reversion',
  },
  { id: 384, name: 'rayquaza', types: ['dragon', 'flying'] },
  {
    id: 384.1,
    name: 'rayquaza-mega',
    types: ['dragon', 'flying'],
    form: 'Mega Evolution',
  },
  { id: 385, name: 'jirachi', types: ['steel', 'psychic'] },
  { id: 386, name: 'deoxys', types: ['psychic'] },
];