/**
 * Generation 6 Pokémon Data
 *
 * @description X, Y, Omega Ruby, Alpha Sapphire - Kalos Region
 * @generation 6
 * @region Kalos
 * @idRange 650-721
 * @features
 *   - Introduced Fairy type and Mega Evolution
 *   - 3D graphics transition
 *   - Retroactively retyped many Pokémon to include Fairy
 * @count 77 Pokémon (including forms and Mega Evolutions)
 */
import type { Pokemon } from './pokemonData';

export const pokemonXY: Pokemon[] = [
  {
    id: 3.1,
    name: 'venusaur-mega',
    types: ['grass', 'poison'],
    form: 'Mega Evolution',
  },
  {
    id: 6.1,
    name: 'charizard-mega-x',
    types: ['fire', 'dragon'],
    form: 'Mega Evolution X',
  },
  {
    id: 6.2,
    name: 'charizard-mega-y',
    types: ['fire', 'flying'],
    form: 'Mega Evolution Y',
  },
  { id: 9.1, name: 'blastoise-mega', types: ['water'], form: 'Mega Evolution' },
  {
    id: 15.1,
    name: 'beedrill-mega',
    types: ['bug', 'poison'],
    form: 'Mega Evolution',
  },
  {
    id: 18.1,
    name: 'pidgeot-mega',
    types: ['normal', 'flying'],
    form: 'Mega Evolution',
  },
  {
    id: 65.1,
    name: 'alakazam-mega',
    types: ['psychic'],
    form: 'Mega Evolution',
  },
  {
    id: 80.1,
    name: 'slowbro-mega',
    types: ['water', 'psychic'],
    form: 'Mega Evolution',
  },
  {
    id: 94.1,
    name: 'gengar-mega',
    types: ['ghost', 'poison'],
    form: 'Mega Evolution',
  },
  {
    id: 115.1,
    name: 'kangaskhan-mega',
    types: ['normal'],
    form: 'Mega Evolution',
  },
  {
    id: 127.1,
    name: 'pinsir-mega',
    types: ['bug', 'flying'],
    form: 'Mega Evolution',
  },
  {
    id: 130.1,
    name: 'gyarados-mega',
    types: ['water', 'dark'],
    form: 'Mega Evolution',
  },
  {
    id: 142.1,
    name: 'aerodactyl-mega',
    types: ['rock', 'flying'],
    form: 'Mega Evolution',
  },
  {
    id: 150.1,
    name: 'mewtwo-mega-x',
    types: ['psychic', 'fighting'],
    form: 'Mega Evolution X',
  },
  {
    id: 150.2,
    name: 'mewtwo-mega-y',
    types: ['psychic'],
    form: 'Mega Evolution Y',
  },
  {
    id: 181.1,
    name: 'ampharos-mega',
    types: ['electric', 'dragon'],
    form: 'Mega Evolution',
  },
  {
    id: 208.1,
    name: 'steelix-mega',
    types: ['steel', 'ground'],
    form: 'Mega Evolution',
  },
  {
    id: 212.1,
    name: 'scizor-mega',
    types: ['bug', 'steel'],
    form: 'Mega Evolution',
  },
  {
    id: 214.1,
    name: 'heracross-mega',
    types: ['bug', 'fighting'],
    form: 'Mega Evolution',
  },
  {
    id: 229.1,
    name: 'houndoom-mega',
    types: ['dark', 'fire'],
    form: 'Mega Evolution',
  },
  {
    id: 248.1,
    name: 'tyranitar-mega',
    types: ['rock', 'dark'],
    form: 'Mega Evolution',
  },
  {
    id: 254.1,
    name: 'sceptile-mega',
    types: ['grass', 'dragon'],
    form: 'Mega Evolution',
  },
  {
    id: 257.1,
    name: 'blaziken-mega',
    types: ['fire', 'fighting'],
    form: 'Mega Evolution',
  },
  {
    id: 260.1,
    name: 'swampert-mega',
    types: ['water', 'ground'],
    form: 'Mega Evolution',
  },
  {
    id: 282.1,
    name: 'gardevoir-mega',
    types: ['psychic', 'fairy'],
    form: 'Mega Evolution',
  },
  {
    id: 302.1,
    name: 'sableye-mega',
    types: ['dark', 'ghost'],
    form: 'Mega Evolution',
  },
  {
    id: 303.1,
    name: 'mawile-mega',
    types: ['steel', 'fairy'],
    form: 'Mega Evolution',
  },
  { id: 306.1, name: 'aggron-mega', types: ['steel'], form: 'Mega Evolution' },
  {
    id: 308.1,
    name: 'medicham-mega',
    types: ['fighting', 'psychic'],
    form: 'Mega Evolution',
  },
  {
    id: 310.1,
    name: 'manectric-mega',
    types: ['electric'],
    form: 'Mega Evolution',
  },
  {
    id: 319.1,
    name: 'sharpedo-mega',
    types: ['water', 'dark'],
    form: 'Mega Evolution',
  },
  {
    id: 323.1,
    name: 'camerupt-mega',
    types: ['fire', 'ground'],
    form: 'Mega Evolution',
  },
  {
    id: 334.1,
    name: 'altaria-mega',
    types: ['dragon', 'fairy'],
    form: 'Mega Evolution',
  },
  { id: 354.1, name: 'banette-mega', types: ['ghost'], form: 'Mega Evolution' },
  { id: 359.1, name: 'absol-mega', types: ['dark'], form: 'Mega Evolution' },
  { id: 362.1, name: 'glalie-mega', types: ['ice'], form: 'Mega Evolution' },
  {
    id: 373.1,
    name: 'salamence-mega',
    types: ['dragon', 'flying'],
    form: 'Mega Evolution',
  },
  {
    id: 376.1,
    name: 'metagross-mega',
    types: ['steel', 'psychic'],
    form: 'Mega Evolution',
  },
  {
    id: 380.1,
    name: 'latias-mega',
    types: ['dragon', 'psychic'],
    form: 'Mega Evolution',
  },
  {
    id: 381.1,
    name: 'latios-mega',
    types: ['dragon', 'psychic'],
    form: 'Mega Evolution',
  },
  {
    id: 382.1,
    name: 'kyogre-primal',
    types: ['water'],
    form: 'Primal Reversion',
  },
  {
    id: 383.1,
    name: 'groudon-primal',
    types: ['ground', 'fire'],
    form: 'Primal Reversion',
  },
  {
    id: 384.1,
    name: 'rayquaza-mega',
    types: ['dragon', 'flying'],
    form: 'Mega Evolution',
  },
  {
    id: 428.1,
    name: 'lopunny-mega',
    types: ['normal', 'fighting'],
    form: 'Mega Evolution',
  },
  {
    id: 445.1,
    name: 'garchomp-mega',
    types: ['dragon', 'ground'],
    form: 'Mega Evolution',
  },
  {
    id: 448.1,
    name: 'lucario-mega',
    types: ['fighting', 'steel'],
    form: 'Mega Evolution',
  },
  {
    id: 460.1,
    name: 'abomasnow-mega',
    types: ['grass', 'ice'],
    form: 'Mega Evolution',
  },
  {
    id: 475.1,
    name: 'gallade-mega',
    types: ['psychic', 'fighting'],
    form: 'Mega Evolution',
  },
  {
    id: 531.1,
    name: 'audino-mega',
    types: ['normal', 'fairy'],
    form: 'Mega Evolution',
  },
  { id: 650, name: 'chespin', types: ['grass'] },
  { id: 651, name: 'quilladin', types: ['grass'] },
  { id: 652, name: 'chesnaught', types: ['grass', 'fighting'] },
  { id: 653, name: 'fennekin', types: ['fire'] },
  { id: 654, name: 'braixen', types: ['fire'] },
  { id: 655, name: 'delphox', types: ['fire', 'psychic'] },
  { id: 656, name: 'froakie', types: ['water'] },
  { id: 657, name: 'frogadier', types: ['water'] },
  { id: 658, name: 'greninja', types: ['water', 'dark'] },
  {
    id: 658.1,
    name: 'greninja-ash',
    types: ['water', 'dark'],
    form: 'Ash-Greninja',
  },
  { id: 659, name: 'bunnelby', types: ['normal'] },
  { id: 660, name: 'diggersby', types: ['normal', 'ground'] },
  { id: 661, name: 'fletchling', types: ['normal', 'flying'] },
  { id: 662, name: 'fletchinder', types: ['fire', 'flying'] },
  { id: 663, name: 'talonflame', types: ['fire', 'flying'] },
  { id: 664, name: 'scatterbug', types: ['bug'] },
  { id: 665, name: 'spewpa', types: ['bug'] },
  { id: 666, name: 'vivillon', types: ['bug', 'flying'] },
  { id: 667, name: 'litleo', types: ['fire', 'normal'] },
  { id: 668, name: 'pyroar', types: ['fire', 'normal'] },
  { id: 669, name: 'flabebe', types: ['fairy'] },
  { id: 670, name: 'floette', types: ['fairy'] },
  { id: 671, name: 'florges', types: ['fairy'] },
  { id: 672, name: 'skiddo', types: ['grass'] },
  { id: 673, name: 'gogoat', types: ['grass'] },
  { id: 674, name: 'pancham', types: ['fighting'] },
  { id: 675, name: 'pangoro', types: ['fighting', 'dark'] },
  { id: 676, name: 'furfrou', types: ['normal'] },
  { id: 677, name: 'espurr', types: ['psychic'] },
  { id: 678, name: 'meowstic', types: ['psychic'] },
  { id: 679, name: 'honedge', types: ['steel', 'ghost'] },
  { id: 680, name: 'doublade', types: ['steel', 'ghost'] },
  { id: 681, name: 'aegislash', types: ['steel', 'ghost'] },
  { id: 682, name: 'spritzee', types: ['fairy'] },
  { id: 683, name: 'aromatisse', types: ['fairy'] },
  { id: 684, name: 'swirlix', types: ['fairy'] },
  { id: 685, name: 'slurpuff', types: ['fairy'] },
  { id: 686, name: 'inkay', types: ['dark', 'psychic'] },
  { id: 687, name: 'malamar', types: ['dark', 'psychic'] },
  { id: 688, name: 'binacle', types: ['rock', 'water'] },
  { id: 689, name: 'barbaracle', types: ['rock', 'water'] },
  { id: 690, name: 'skrelp', types: ['poison', 'water'] },
  { id: 691, name: 'dragalge', types: ['poison', 'dragon'] },
  { id: 692, name: 'clauncher', types: ['water'] },
  { id: 693, name: 'clawitzer', types: ['water'] },
  { id: 694, name: 'helioptile', types: ['electric', 'normal'] },
  { id: 695, name: 'heliolisk', types: ['electric', 'normal'] },
  { id: 696, name: 'tyrunt', types: ['rock', 'dragon'] },
  { id: 697, name: 'tyrantrum', types: ['rock', 'dragon'] },
  { id: 698, name: 'amaura', types: ['rock', 'ice'] },
  { id: 699, name: 'aurorus', types: ['rock', 'ice'] },
  { id: 700, name: 'sylveon', types: ['fairy'] },
  { id: 701, name: 'hawlucha', types: ['fighting', 'flying'] },
  { id: 702, name: 'dedenne', types: ['electric', 'fairy'] },
  { id: 703, name: 'carbink', types: ['rock', 'fairy'] },
  { id: 704, name: 'goomy', types: ['dragon'] },
  { id: 705, name: 'sliggoo', types: ['dragon'] },
  { id: 706, name: 'goodra', types: ['dragon'] },
  { id: 707, name: 'klefki', types: ['steel', 'fairy'] },
  { id: 708, name: 'phantump', types: ['ghost', 'grass'] },
  { id: 709, name: 'trevenant', types: ['ghost', 'grass'] },
  { id: 710, name: 'pumpkaboo', types: ['ghost', 'grass'] },
  { id: 711, name: 'gourgeist', types: ['ghost', 'grass'] },
  { id: 712, name: 'bergmite', types: ['ice'] },
  { id: 713, name: 'avalugg', types: ['ice'] },
  { id: 714, name: 'noibat', types: ['flying', 'dragon'] },
  { id: 715, name: 'noivern', types: ['flying', 'dragon'] },
  { id: 716, name: 'xerneas', types: ['fairy'] },
  { id: 717, name: 'yveltal', types: ['dark', 'flying'] },
  { id: 718, name: 'zygarde', types: ['dragon', 'ground'] },
  { id: 719, name: 'diancie', types: ['rock', 'fairy'] },
  {
    id: 719.1,
    name: 'diancie-mega',
    types: ['rock', 'fairy'],
    form: 'Mega Evolution',
  },
  { id: 720, name: 'hoopa', types: ['psychic', 'ghost'] },
  { id: 721, name: 'volcanion', types: ['fire', 'water'] },
];
