// Generation 1 (001-151) - Red, Blue, Green, Yellow
// Kanto Region Pokémon
export const pokemonRBGY = [
  { id: 1, name: 'bulbasaur', types: ['grass', 'poison'] },
  { id: 2, name: 'ivysaur', types: ['grass', 'poison'] },
  { id: 3, name: 'venusaur', types: ['grass', 'poison'] },
  {
    id: 3.1,
    name: 'venusaur-mega',
    types: ['grass', 'poison'],
    form: 'Mega Evolution',
  },
  { id: 4, name: 'charmander', types: ['fire'] },
  { id: 5, name: 'charmeleon', types: ['fire'] },
  { id: 6, name: 'charizard', types: ['fire', 'flying'] },
  {
    id: 6.1,
    name: 'charizard-mega-x',
    types: ['fire', 'dragon'],
    form: 'Mega Evolution X',
  },
  {
    id: 6.2,
    name: 'charizard-mega-y',
    types: ['fire', 'flying'],
    form: 'Mega Evolution Y',
  },
  { id: 7, name: 'squirtle', types: ['water'] },
  { id: 8, name: 'wartortle', types: ['water'] },
  { id: 9, name: 'blastoise', types: ['water'] },
  { id: 9.1, name: 'blastoise-mega', types: ['water'], form: 'Mega Evolution' },
  { id: 10, name: 'caterpie', types: ['bug'] },
  { id: 11, name: 'metapod', types: ['bug'] },
  { id: 12, name: 'butterfree', types: ['bug', 'flying'] },
  { id: 13, name: 'weedle', types: ['bug', 'poison'] },
  { id: 14, name: 'kakuna', types: ['bug', 'poison'] },
  { id: 15, name: 'beedrill', types: ['bug', 'poison'] },
  {
    id: 15.1,
    name: 'beedrill-mega',
    types: ['bug', 'poison'],
    form: 'Mega Evolution',
  },
  { id: 16, name: 'pidgey', types: ['normal', 'flying'] },
  { id: 17, name: 'pidgeotto', types: ['normal', 'flying'] },
  { id: 18, name: 'pidgeot', types: ['normal', 'flying'] },
  {
    id: 18.1,
    name: 'pidgeot-mega',
    types: ['normal', 'flying'],
    form: 'Mega Evolution',
  },
  { id: 19, name: 'rattata', types: ['normal'] },
  {
    id: 19.1,
    name: 'rattata-alolan',
    types: ['dark', 'normal'],
    region: 'Alola',
  },
  { id: 20, name: 'raticate', types: ['normal'] },
  {
    id: 20.1,
    name: 'raticate-alolan',
    types: ['dark', 'normal'],
    region: 'Alola',
  },
  { id: 21, name: 'spearow', types: ['normal', 'flying'] },
  { id: 22, name: 'fearow', types: ['normal', 'flying'] },
  { id: 23, name: 'ekans', types: ['poison'] },
  { id: 24, name: 'arbok', types: ['poison'] },
  { id: 25, name: 'pikachu', types: ['electric'] },
  { id: 26, name: 'raichu', types: ['electric'] },
  {
    id: 26.1,
    name: 'raichu-alolan',
    types: ['electric', 'psychic'],
    region: 'Alola',
  },
  { id: 27, name: 'sandshrew', types: ['ground'] },
  {
    id: 27.1,
    name: 'sandshrew-alolan',
    types: ['ice', 'steel'],
    region: 'Alola',
  },
  { id: 28, name: 'sandslash', types: ['ground'] },
  {
    id: 28.1,
    name: 'sandslash-alolan',
    types: ['ice', 'steel'],
    region: 'Alola',
  },
  { id: 29, name: 'nidoran-f', types: ['poison'] },
  { id: 30, name: 'nidorina', types: ['poison'] },
  { id: 31, name: 'nidoqueen', types: ['poison', 'ground'] },
  { id: 32, name: 'nidoran-m', types: ['poison'] },
  { id: 33, name: 'nidorino', types: ['poison'] },
  { id: 34, name: 'nidoking', types: ['poison', 'ground'] },
  {
    id: 35,
    name: 'clefairy',
    types: ['fairy'],
    generationTypes: { 1: ['normal'], 6: ['fairy'] },
  },
  {
    id: 36,
    name: 'clefable',
    types: ['fairy'],
    generationTypes: { 1: ['normal'], 6: ['fairy'] },
  },
  { id: 37, name: 'vulpix', types: ['fire'] },
  { id: 37.1, name: 'vulpix-alolan', types: ['ice'], region: 'Alola' },
  { id: 38, name: 'ninetales', types: ['fire'] },
  {
    id: 38.1,
    name: 'ninetales-alolan',
    types: ['ice', 'fairy'],
    region: 'Alola',
  },
  {
    id: 39,
    name: 'jigglypuff',
    types: ['normal', 'fairy'],
    generationTypes: { 1: ['normal'], 6: ['normal', 'fairy'] },
  },
  {
    id: 40,
    name: 'wigglytuff',
    types: ['normal', 'fairy'],
    generationTypes: { 1: ['normal'], 6: ['normal', 'fairy'] },
  },
  { id: 41, name: 'zubat', types: ['poison', 'flying'] },
  { id: 42, name: 'golbat', types: ['poison', 'flying'] },
  { id: 43, name: 'oddish', types: ['grass', 'poison'] },
  { id: 44, name: 'gloom', types: ['grass', 'poison'] },
  { id: 45, name: 'vileplume', types: ['grass', 'poison'] },
  { id: 46, name: 'paras', types: ['bug', 'grass'] },
  { id: 47, name: 'parasect', types: ['bug', 'grass'] },
  { id: 48, name: 'venonat', types: ['bug', 'poison'] },
  { id: 49, name: 'venomoth', types: ['bug', 'poison'] },
  { id: 50, name: 'diglett', types: ['ground'] },
  {
    id: 50.1,
    name: 'diglett-alolan',
    types: ['ground', 'steel'],
    region: 'Alola',
  },
  { id: 51, name: 'dugtrio', types: ['ground'] },
  {
    id: 51.1,
    name: 'dugtrio-alolan',
    types: ['ground', 'steel'],
    region: 'Alola',
  },
  { id: 52, name: 'meowth', types: ['normal'] },
  { id: 52.1, name: 'meowth-alolan', types: ['dark'], region: 'Alola' },
  { id: 52.2, name: 'meowth-galarian', types: ['steel'], region: 'Galar' },
  { id: 53, name: 'persian', types: ['normal'] },
  { id: 53.1, name: 'persian-alolan', types: ['dark'], region: 'Alola' },
  { id: 54, name: 'psyduck', types: ['water'] },
  { id: 55, name: 'golduck', types: ['water'] },
  { id: 56, name: 'mankey', types: ['fighting'] },
  { id: 57, name: 'primeape', types: ['fighting'] },
  { id: 58, name: 'growlithe', types: ['fire'] },
  {
    id: 58.1,
    name: 'growlithe-hisuian',
    types: ['fire', 'rock'],
    region: 'Hisui',
  },
  { id: 59, name: 'arcanine', types: ['fire'] },
  {
    id: 59.1,
    name: 'arcanine-hisuian',
    types: ['fire', 'rock'],
    region: 'Hisui',
  },
  { id: 60, name: 'poliwag', types: ['water'] },
  { id: 61, name: 'poliwhirl', types: ['water'] },
  { id: 62, name: 'poliwrath', types: ['water', 'fighting'] },
  { id: 63, name: 'abra', types: ['psychic'] },
  { id: 64, name: 'kadabra', types: ['psychic'] },
  { id: 65, name: 'alakazam', types: ['psychic'] },
  {
    id: 65.1,
    name: 'alakazam-mega',
    types: ['psychic'],
    form: 'Mega Evolution',
  },
  { id: 66, name: 'machop', types: ['fighting'] },
  { id: 67, name: 'machoke', types: ['fighting'] },
  { id: 68, name: 'machamp', types: ['fighting'] },
  { id: 69, name: 'bellsprout', types: ['grass', 'poison'] },
  { id: 70, name: 'weepinbell', types: ['grass', 'poison'] },
  { id: 71, name: 'victreebel', types: ['grass', 'poison'] },
  { id: 72, name: 'tentacool', types: ['water', 'poison'] },
  { id: 73, name: 'tentacruel', types: ['water', 'poison'] },
  { id: 74, name: 'geodude', types: ['rock', 'ground'] },
  {
    id: 74.1,
    name: 'geodude-alolan',
    types: ['rock', 'electric'],
    region: 'Alola',
  },
  { id: 75, name: 'graveler', types: ['rock', 'ground'] },
  {
    id: 75.1,
    name: 'graveler-alolan',
    types: ['rock', 'electric'],
    region: 'Alola',
  },
  { id: 76, name: 'golem', types: ['rock', 'ground'] },
  {
    id: 76.1,
    name: 'golem-alolan',
    types: ['rock', 'electric'],
    region: 'Alola',
  },
  { id: 77, name: 'ponyta', types: ['fire'] },
  { id: 77.1, name: 'ponyta-galarian', types: ['psychic'], region: 'Galar' },
  { id: 78, name: 'rapidash', types: ['fire'] },
  {
    id: 78.1,
    name: 'rapidash-galarian',
    types: ['psychic', 'fairy'],
    region: 'Galar',
  },
  { id: 79, name: 'slowpoke', types: ['water', 'psychic'] },
  { id: 79.1, name: 'slowpoke-galarian', types: ['psychic'], region: 'Galar' },
  { id: 80, name: 'slowbro', types: ['water', 'psychic'] },
  {
    id: 80.1,
    name: 'slowbro-mega',
    types: ['water', 'psychic'],
    form: 'Mega Evolution',
  },
  {
    id: 80.2,
    name: 'slowbro-galarian',
    types: ['poison', 'psychic'],
    region: 'Galar',
  },
  {
    id: 81,
    name: 'magnemite',
    types: ['electric', 'steel'],
    generationTypes: { 1: ['electric'], 2: ['electric', 'steel'] },
  },
  {
    id: 82,
    name: 'magneton',
    types: ['electric', 'steel'],
    generationTypes: { 1: ['electric'], 2: ['electric', 'steel'] },
  },
  { id: 83, name: 'farfetchd', types: ['normal', 'flying'] },
  {
    id: 83.1,
    name: 'farfetchd-galarian',
    types: ['fighting'],
    region: 'Galar',
  },
  { id: 84, name: 'doduo', types: ['normal', 'flying'] },
  { id: 85, name: 'dodrio', types: ['normal', 'flying'] },
  { id: 86, name: 'seel', types: ['water'] },
  { id: 87, name: 'dewgong', types: ['water', 'ice'] },
  { id: 88, name: 'grimer', types: ['poison'] },
  {
    id: 88.1,
    name: 'grimer-alolan',
    types: ['poison', 'dark'],
    region: 'Alola',
  },
  { id: 89, name: 'muk', types: ['poison'] },
  { id: 89.1, name: 'muk-alolan', types: ['poison', 'dark'], region: 'Alola' },
  { id: 90, name: 'shellder', types: ['water'] },
  { id: 91, name: 'cloyster', types: ['water', 'ice'] },
  { id: 92, name: 'gastly', types: ['ghost', 'poison'] },
  { id: 93, name: 'haunter', types: ['ghost', 'poison'] },
  { id: 94, name: 'gengar', types: ['ghost', 'poison'] },
  {
    id: 94.1,
    name: 'gengar-mega',
    types: ['ghost', 'poison'],
    form: 'Mega Evolution',
  },
  { id: 95, name: 'onix', types: ['rock', 'ground'] },
  { id: 96, name: 'drowzee', types: ['psychic'] },
  { id: 97, name: 'hypno', types: ['psychic'] },
  { id: 98, name: 'krabby', types: ['water'] },
  { id: 99, name: 'kingler', types: ['water'] },
  { id: 100, name: 'voltorb', types: ['electric'] },
  {
    id: 100.1,
    name: 'voltorb-hisuian',
    types: ['electric', 'grass'],
    region: 'Hisui',
  },
  { id: 101, name: 'electrode', types: ['electric'] },
  {
    id: 101.1,
    name: 'electrode-hisuian',
    types: ['electric', 'grass'],
    region: 'Hisui',
  },
  { id: 102, name: 'exeggcute', types: ['grass', 'psychic'] },
  { id: 103, name: 'exeggutor', types: ['grass', 'psychic'] },
  {
    id: 103.1,
    name: 'exeggutor-alolan',
    types: ['grass', 'dragon'],
    region: 'Alola',
  },
  { id: 104, name: 'cubone', types: ['ground'] },
  { id: 105, name: 'marowak', types: ['ground'] },
  {
    id: 105.1,
    name: 'marowak-alolan',
    types: ['fire', 'ghost'],
    region: 'Alola',
  },
  { id: 106, name: 'hitmonlee', types: ['fighting'] },
  { id: 107, name: 'hitmonchan', types: ['fighting'] },
  { id: 108, name: 'lickitung', types: ['normal'] },
  { id: 109, name: 'koffing', types: ['poison'] },
  { id: 110, name: 'weezing', types: ['poison'] },
  {
    id: 110.1,
    name: 'weezing-galarian',
    types: ['poison', 'fairy'],
    region: 'Galar',
  },
  { id: 111, name: 'rhyhorn', types: ['ground', 'rock'] },
  { id: 112, name: 'rhydon', types: ['ground', 'rock'] },
  { id: 113, name: 'chansey', types: ['normal'] },
  { id: 114, name: 'tangela', types: ['grass'] },
  { id: 115, name: 'kangaskhan', types: ['normal'] },
  {
    id: 115.1,
    name: 'kangaskhan-mega',
    types: ['normal'],
    form: 'Mega Evolution',
  },
  { id: 116, name: 'horsea', types: ['water'] },
  { id: 117, name: 'seadra', types: ['water'] },
  { id: 118, name: 'goldeen', types: ['water'] },
  { id: 119, name: 'seaking', types: ['water'] },
  { id: 120, name: 'staryu', types: ['water'] },
  { id: 121, name: 'starmie', types: ['water', 'psychic'] },
  {
    id: 122,
    name: 'mr-mime',
    types: ['psychic', 'fairy'],
    generationTypes: { 1: ['psychic'], 6: ['psychic', 'fairy'] },
  },
  {
    id: 122.1,
    name: 'mr-mime-galarian',
    types: ['ice', 'psychic'],
    region: 'Galar',
  },
  { id: 123, name: 'scyther', types: ['bug', 'flying'] },
  { id: 124, name: 'jynx', types: ['ice', 'psychic'] },
  { id: 125, name: 'electabuzz', types: ['electric'] },
  { id: 126, name: 'magmar', types: ['fire'] },
  { id: 127, name: 'pinsir', types: ['bug'] },
  {
    id: 127.1,
    name: 'pinsir-mega',
    types: ['bug', 'flying'],
    form: 'Mega Evolution',
  },
  { id: 128, name: 'tauros', types: ['normal'] },
  {
    id: 128.1,
    name: 'tauros-paldean-combat',
    types: ['fighting'],
    region: 'Paldea',
    form: 'Combat Breed',
  },
  {
    id: 128.2,
    name: 'tauros-paldean-blaze',
    types: ['fighting', 'fire'],
    region: 'Paldea',
    form: 'Blaze Breed',
  },
  {
    id: 128.3,
    name: 'tauros-paldean-aqua',
    types: ['fighting', 'water'],
    region: 'Paldea',
    form: 'Aqua Breed',
  },
  { id: 129, name: 'magikarp', types: ['water'] },
  { id: 130, name: 'gyarados', types: ['water', 'flying'] },
  {
    id: 130.1,
    name: 'gyarados-mega',
    types: ['water', 'dark'],
    form: 'Mega Evolution',
  },
  { id: 131, name: 'lapras', types: ['water', 'ice'] },
  { id: 132, name: 'ditto', types: ['normal'] },
  { id: 133, name: 'eevee', types: ['normal'] },
  { id: 134, name: 'vaporeon', types: ['water'] },
  { id: 135, name: 'jolteon', types: ['electric'] },
  { id: 136, name: 'flareon', types: ['fire'] },
  { id: 137, name: 'porygon', types: ['normal'] },
  { id: 138, name: 'omanyte', types: ['rock', 'water'] },
  { id: 139, name: 'omastar', types: ['rock', 'water'] },
  { id: 140, name: 'kabuto', types: ['rock', 'water'] },
  { id: 141, name: 'kabutops', types: ['rock', 'water'] },
  { id: 142, name: 'aerodactyl', types: ['rock', 'flying'] },
  {
    id: 142.1,
    name: 'aerodactyl-mega',
    types: ['rock', 'flying'],
    form: 'Mega Evolution',
  },
  { id: 143, name: 'snorlax', types: ['normal'] },
  { id: 144, name: 'articuno', types: ['ice', 'flying'] },
  {
    id: 144.1,
    name: 'articuno-galarian',
    types: ['psychic', 'flying'],
    region: 'Galar',
  },
  { id: 145, name: 'zapdos', types: ['electric', 'flying'] },
  {
    id: 145.1,
    name: 'zapdos-galarian',
    types: ['fighting', 'flying'],
    region: 'Galar',
  },
  { id: 146, name: 'moltres', types: ['fire', 'flying'] },
  {
    id: 146.1,
    name: 'moltres-galarian',
    types: ['dark', 'flying'],
    region: 'Galar',
  },
  { id: 147, name: 'dratini', types: ['dragon'] },
  { id: 148, name: 'dragonair', types: ['dragon'] },
  { id: 149, name: 'dragonite', types: ['dragon', 'flying'] },
  { id: 150, name: 'mewtwo', types: ['psychic'] },
  {
    id: 150.1,
    name: 'mewtwo-mega-x',
    types: ['psychic', 'fighting'],
    form: 'Mega Evolution X',
  },
  {
    id: 150.2,
    name: 'mewtwo-mega-y',
    types: ['psychic'],
    form: 'Mega Evolution Y',
  },
  { id: 151, name: 'mew', types: ['psychic'] },
];