/**
 * Generation 8 Pokémon Data
 * 
 * @description Sword, Shield, Brilliant Diamond, Shining Pearl, Legends: Arceus - Galar/Hisui Regions
 * @generation 8
 * @region Galar/Hisui
 * @idRange 810-905
 * @features
 *   - Introduced Dynamax/Gigantamax mechanics
 *   - Galarian and Hisuian regional variants
 *   - New evolution methods and Noble Pokémon
 * @count 93 Pokémon (including forms)
 */
import type { Pokemon } from './pokemonData';

export const pokemonSwSh: Pokemon[] = [
  { id: 52.2, name: 'meowth-galarian', types: ['steel'], region: 'Galar' },
  { id: 77.1, name: 'ponyta-galarian', types: ['psychic'], region: 'Galar' },
  {
    id: 78.1,
    name: 'rapidash-galarian',
    types: ['psychic', 'fairy'],
    region: 'Galar',
  },
  { id: 79.1, name: 'slowpoke-galarian', types: ['psychic'], region: 'Galar' },
  {
    id: 80.2,
    name: 'slowbro-galarian',
    types: ['poison', 'psychic'],
    region: 'Galar',
  },
  {
    id: 83.1,
    name: 'farfetchd-galarian',
    types: ['fighting'],
    region: 'Galar',
  },
  {
    id: 110.1,
    name: 'weezing-galarian',
    types: ['poison', 'fairy'],
    region: 'Galar',
  },
  {
    id: 122.1,
    name: 'mr-mime-galarian',
    types: ['ice', 'psychic'],
    region: 'Galar',
  },
  {
    id: 144.1,
    name: 'articuno-galarian',
    types: ['psychic', 'flying'],
    region: 'Galar',
  },
  {
    id: 145.1,
    name: 'zapdos-galarian',
    types: ['fighting', 'flying'],
    region: 'Galar',
  },
  {
    id: 146.1,
    name: 'moltres-galarian',
    types: ['dark', 'flying'],
    region: 'Galar',
  },
  {
    id: 199.1,
    name: 'slowking-galarian',
    types: ['poison', 'psychic'],
    region: 'Galar',
  },
  { id: 222.1, name: 'corsola-galarian', types: ['ghost'], region: 'Galar' },
  {
    id: 263.1,
    name: 'zigzagoon-galarian',
    types: ['dark', 'normal'],
    region: 'Galar',
  },
  {
    id: 264.1,
    name: 'linoone-galarian',
    types: ['dark', 'normal'],
    region: 'Galar',
  },
  { id: 810, name: 'grookey', types: ['grass'] },
  { id: 811, name: 'thwackey', types: ['grass'] },
  { id: 812, name: 'rillaboom', types: ['grass'] },
  { id: 813, name: 'scorbunny', types: ['fire'] },
  { id: 814, name: 'raboot', types: ['fire'] },
  { id: 815, name: 'cinderace', types: ['fire'] },
  { id: 816, name: 'sobble', types: ['water'] },
  { id: 817, name: 'drizzile', types: ['water'] },
  { id: 818, name: 'inteleon', types: ['water'] },
  { id: 819, name: 'skwovet', types: ['normal'] },
  { id: 820, name: 'greedent', types: ['normal'] },
  { id: 821, name: 'rookidee', types: ['flying'] },
  { id: 822, name: 'corvisquire', types: ['flying'] },
  { id: 823, name: 'corviknight', types: ['flying', 'steel'] },
  { id: 824, name: 'blipbug', types: ['bug'] },
  { id: 825, name: 'dottler', types: ['bug', 'psychic'] },
  { id: 826, name: 'orbeetle', types: ['bug', 'psychic'] },
  { id: 827, name: 'nickit', types: ['dark'] },
  { id: 828, name: 'thievul', types: ['dark'] },
  { id: 829, name: 'gossifleur', types: ['grass'] },
  { id: 830, name: 'eldegoss', types: ['grass'] },
  { id: 831, name: 'wooloo', types: ['normal'] },
  { id: 832, name: 'dubwool', types: ['normal'] },
  { id: 833, name: 'chewtle', types: ['water'] },
  { id: 834, name: 'drednaw', types: ['water', 'rock'] },
  { id: 835, name: 'yamper', types: ['electric'] },
  { id: 836, name: 'boltund', types: ['electric'] },
  { id: 837, name: 'rolycoly', types: ['rock'] },
  { id: 838, name: 'carkol', types: ['rock', 'fire'] },
  { id: 839, name: 'coalossal', types: ['rock', 'fire'] },
  { id: 840, name: 'applin', types: ['grass', 'dragon'] },
  { id: 841, name: 'flapple', types: ['grass', 'dragon'] },
  { id: 842, name: 'appletun', types: ['grass', 'dragon'] },
  { id: 843, name: 'silicobra', types: ['ground'] },
  { id: 844, name: 'sandaconda', types: ['ground'] },
  { id: 845, name: 'cramorant', types: ['flying', 'water'] },
  { id: 846, name: 'arrokuda', types: ['water'] },
  { id: 847, name: 'barraskewda', types: ['water'] },
  { id: 848, name: 'toxel', types: ['electric', 'poison'] },
  { id: 849, name: 'toxapex', types: ['electric', 'poison'] },
  { id: 850, name: 'sizzlipede', types: ['fire', 'bug'] },
  { id: 851, name: 'centiskorch', types: ['fire', 'bug'] },
  { id: 852, name: 'clobbopus', types: ['fighting'] },
  { id: 853, name: 'grapploct', types: ['fighting'] },
  { id: 854, name: 'sinistea', types: ['ghost'] },
  { id: 855, name: 'polteageist', types: ['ghost'] },
  { id: 856, name: 'hatenna', types: ['psychic'] },
  { id: 857, name: 'hattrem', types: ['psychic'] },
  { id: 858, name: 'hatterene', types: ['psychic', 'fairy'] },
  { id: 859, name: 'impidimp', types: ['dark', 'fairy'] },
  { id: 860, name: 'morgrem', types: ['dark', 'fairy'] },
  { id: 861, name: 'grimmsnarl', types: ['dark', 'fairy'] },
  { id: 862, name: 'obstagoon', types: ['dark', 'normal'] },
  { id: 863, name: 'perrserker', types: ['steel'] },
  { id: 864, name: 'cursola', types: ['ghost'] },
  { id: 865, name: 'sirfetchd', types: ['fighting'] },
  { id: 866, name: 'mr-rime', types: ['ice', 'psychic'] },
  { id: 867, name: 'runerigus', types: ['ground', 'ghost'] },
  { id: 868, name: 'milcery', types: ['fairy'] },
  { id: 869, name: 'alcremie', types: ['fairy'] },
  { id: 870, name: 'falinks', types: ['fighting'] },
  { id: 871, name: 'pincurchin', types: ['electric'] },
  { id: 872, name: 'snom', types: ['ice', 'bug'] },
  { id: 873, name: 'frosmoth', types: ['ice', 'bug'] },
  { id: 874, name: 'stonjourner', types: ['rock'] },
  { id: 875, name: 'eiscue', types: ['ice'] },
  { id: 876, name: 'indeedee', types: ['psychic', 'normal'] },
  { id: 877, name: 'morpeko', types: ['electric', 'dark'] },
  { id: 878, name: 'cufant', types: ['steel'] },
  { id: 879, name: 'copperajah', types: ['steel'] },
  { id: 880, name: 'dracozolt', types: ['electric', 'dragon'] },
  { id: 881, name: 'arctozolt', types: ['electric', 'ice'] },
  { id: 882, name: 'dracovish', types: ['water', 'dragon'] },
  { id: 883, name: 'arctovish', types: ['water', 'ice'] },
  { id: 884, name: 'duraludon', types: ['steel', 'dragon'] },
  { id: 885, name: 'dreepy', types: ['dragon', 'ghost'] },
  { id: 886, name: 'drakloak', types: ['dragon', 'ghost'] },
  { id: 887, name: 'dragapult', types: ['dragon', 'ghost'] },
  { id: 888, name: 'zacian', types: ['fairy'] },
  {
    id: 888.1,
    name: 'zacian-crowned',
    types: ['fairy', 'steel'],
    form: 'Crowned Sword',
  },
  { id: 889, name: 'zamazenta', types: ['fighting'] },
  {
    id: 889.1,
    name: 'zamazenta-crowned',
    types: ['fighting', 'steel'],
    form: 'Crowned Shield',
  },
  { id: 890, name: 'eternatus', types: ['poison', 'dragon'] },
  { id: 891, name: 'kubfu', types: ['fighting'] },
  { id: 892, name: 'urshifu', types: ['fighting', 'dark'] },
  {
    id: 892.1,
    name: 'urshifu-rapid-strike',
    types: ['fighting', 'water'],
    form: 'Rapid Strike Style',
  },
  { id: 893, name: 'zarude', types: ['dark', 'grass'] },
  { id: 894, name: 'regieleki', types: ['electric'] },
  { id: 895, name: 'regidrago', types: ['dragon'] },
  { id: 896, name: 'glastrier', types: ['ice'] },
  { id: 897, name: 'spectrier', types: ['ghost'] },
  { id: 898, name: 'calyrex', types: ['psychic', 'grass'] }
];
